### ISSUE TITLE
[강의 상세] - 리뷰 없을 경우 로딩화면 삭제 필요

### ISSUE THREAD

**Issue by nightohl** [pungdong/PungDong#185]
리뷰가 없는 경우 리뷰컴포넌트가 계속 로딩중인 것 처럼 보이는 것 수정 필요

![Simulator Screen Shot - iPhone 12 - 2021-07-25 at 12 12 49](https://user-images.githubusercontent.com/48432932/126886500-40833b71-44f8-489b-b247-78bc856bd98d.png)

**Comment by kym123123** [comment]
완료
