### ISSUE TITLE
[강의 상세] - 리뷰 필터링 그림자 적용 수정

### ISSUE THREAD

**Issue by nightohl** [pungdong/PungDong#186]
바깥쪽 컨에이너에 그림자가 적용되도록 수정 필요

![Simulator Screen Shot - iPhone 12 - 2021-07-25 at 12 16 35](https://user-images.githubusercontent.com/48432932/126886520-81951cf2-4c5c-421f-a6d6-c7f39b22269c.png)

**Comment by kym123123** [comment]
완료
