### ISSUE TITLE
[강의 상세] - 리뷰 작성 날짜 표기 필요

### ISSUE THREAD

**Issue by nightohl** [pungdong/PungDong#187]
본문 바로 위에 리뷰 작성날짜 표기 필요

![Simulator Screen Shot - iPhone 12 - 2021-07-25 at 12 19 36](https://user-images.githubusercontent.com/48432932/126886573-1e23189a-6a5c-4452-800b-4612f9acbb90.png)

**Comment by kym123123** [comment]
완료
