### ISSUE TITLE
[로그아웃] 구현 우선순위

### ISSUE THREAD

**Issue by nightohl** [pungdong/PungDong#214]
1. RecoilRoot 끼리 특정 상태를 공유할 수 있는 방법이 있는지

2. 상태에 따라서 스택을 나누지 않고, 큰 스택 트리를 만든다.
	Stack
		compo = 로그인 스택
		compo = 메인 스택
	Stack

3. 맨 바깥에는 context API 또는 redux를 두기

4. RecoilRoot를 하나로 씀 -> 상태 관련된 처리가 끝나고 나가는 시점에 관련 상태 초기화 루틴 다 추가해야함

**Comment by nightohl** [comment]
1번 대안의 구현방안은 RecoilRoot의 override 프롭을 false로 주면 되는데,
도큐먼트에는 override 프롭이 명시돼있지만 현재 우리 프로젝트의 recoil 버전에서는 없는 상태임.

따라서 작업자는 recoil 버전 업데이트를 먼저 해야함

**Comment by park-moen** [comment]
그럼 2번 방식으로 하는게 가장 코드 변경 사항이 많지 않겠군요
